const freezeScene = (scene) => Object.freeze({
  ...scene,
  metrics: Object.freeze(scene.metrics.map(Object.freeze)),
  hourly: Object.freeze(scene.hourly.map(Object.freeze)),
})

export const weatherScenes = Object.freeze([
  freezeScene({
    id: 'sunny',
    label: '晴天',
    englishLabel: 'CLEAR SKY',
    location: '杭州 · 西湖',
    time: '14:28',
    temperature: '28°',
    range: '最高 31° · 最低 22°',
    summary: '阳光明亮，微风舒适',
    accent: '#ffcb67',
    metrics: [
      { label: '体感', value: '29°' },
      { label: '湿度', value: '42%' },
      { label: '紫外线', value: '中等' },
    ],
    hourly: [
      { time: '现在', icon: 'sun', temperature: '28°' },
      { time: '16时', icon: 'sun', temperature: '29°' },
      { time: '18时', icon: 'haze', temperature: '26°' },
      { time: '20时', icon: 'moon', temperature: '24°' },
    ],
  }),
  freezeScene({
    id: 'windy',
    label: '大风',
    englishLabel: 'HIGH WIND',
    location: '青岛 · 崂山',
    time: '14:28',
    temperature: '17°',
    range: '阵风可达 9 级',
    summary: '强劲北风，注意高空坠物',
    accent: '#9fe6dd',
    metrics: [
      { label: '风速', value: '42 km/h' },
      { label: '阵风', value: '68 km/h' },
      { label: '能见度', value: '18 km' },
    ],
    hourly: [
      { time: '现在', icon: 'wind', temperature: '17°' },
      { time: '16时', icon: 'wind', temperature: '16°' },
      { time: '18时', icon: 'cloud', temperature: '15°' },
      { time: '20时', icon: 'moon', temperature: '14°' },
    ],
  }),
  freezeScene({
    id: 'stormy',
    label: '暴雨',
    englishLabel: 'THUNDERSTORM',
    location: '广州 · 天河',
    time: '14:28',
    temperature: '24°',
    range: '暴雨橙色预警',
    summary: '雷雨持续，尽量避免外出',
    accent: '#90aef8',
    metrics: [
      { label: '降水', value: '86 mm' },
      { label: '湿度', value: '94%' },
      { label: '气压', value: '998 hPa' },
    ],
    hourly: [
      { time: '现在', icon: 'storm', temperature: '24°' },
      { time: '16时', icon: 'storm', temperature: '23°' },
      { time: '18时', icon: 'rain', temperature: '22°' },
      { time: '20时', icon: 'rain', temperature: '22°' },
    ],
  }),
  freezeScene({
    id: 'snowy',
    label: '暴雪',
    englishLabel: 'HEAVY SNOW',
    location: '哈尔滨 · 道里',
    time: '14:28',
    temperature: '-12°',
    range: '暴雪蓝色预警',
    summary: '道路结冰，出行注意防滑',
    accent: '#d8edff',
    metrics: [
      { label: '积雪', value: '22 cm' },
      { label: '体感', value: '-19°' },
      { label: '能见度', value: '600 m' },
    ],
    hourly: [
      { time: '现在', icon: 'snow', temperature: '-12°' },
      { time: '16时', icon: 'snow', temperature: '-13°' },
      { time: '18时', icon: 'snow', temperature: '-15°' },
      { time: '20时', icon: 'cloud', temperature: '-16°' },
    ],
  }),
])
